### ISSUE TITLE
Not working "Unknown" sender

### ISSUE THREAD

**Issue by ProggerX** [NotBalds/cwe-rust-cli#1]
If I get message from unknown sender, client panics.
I think it's connected to history.
![IMG_20240817_010544_410.jpg](https://github.com/user-attachments/assets/bbe48498-12f3-4d45-a01a-07910046451b)

**Comment by TBWanderer** [comment]
I don't think it depends on history. The problem is rather that I have not added a handler for receiving a message from an unknown user. Therefore, the program tries to find this user among the recorded ones. I will fix it soon

**Comment by TBWanderer** [comment]
I fixed that issue in 0.3.3
